### ISSUE TITLE
Data documentation

### ISSUE THREAD

**Issue by jsta** [cont-limno/DoLakesFeelTheBurn#1]
Does it need to be cleaned up or organized differently?

**Comment by immccull95** [comment]
I don't think we need to reorganize, do you think so? I think the priority is documenting the files in the ExportedData folder (i.e., columns...what do they mean?). I do need to go in and remove unused files, so that should slim down the folder. Right now all I have is a text file that lists column definitions...what else would you suggest we do?

**Comment by jsta** [comment]
I was just trying to translate your email and leave myself a reminder. We can talk specifics in person.

**Comment by jsta** [comment]
It looks like this can be closed...
